services:
  jupyter:
    build: 
      context: .
      args:
        DIR_WORK: "/usr/src"
        ENV_YML: "environment.yaml"
        VENV: "stats"
        REQ_TXT: "requirements.txt"
    image: tyamadabiodataeng/py-r-stats
    container_name: jupyter
    command: mamba run --name stats jupyter lab --ip=0.0.0.0 --allow-root --LabApp.token=''
    ports:
     - "8888:8888"
    volumes:
     - ./scripts:/usr/src
    tty: true
    stdin_open: true
